export const WAVE_LEVELS = [
  {
    id: 'single-basic',
    name: 'Single Wave',
    mode: 'single',
    A: 1.2,
    f: 1,
    lambda: 4,
    phase2: 0,
    description: 'A single traveling wave. Adjust amplitude, frequency and wavelength to see how each reshapes it.',
  },
  {
    id: 'interference-constructive',
    name: 'Constructive',
    mode: 'interference',
    A: 1,
    f: 1,
    lambda: 4,
    phase2: 0,
    description: 'Two identical waves in phase — their peaks align and amplitudes add together.',
  },
  {
    id: 'interference-destructive',
    name: 'Destructive',
    mode: 'interference',
    A: 1,
    f: 1,
    lambda: 4,
    phase2: 180,
    description: 'Two identical waves exactly out of phase — peaks cancel troughs, flattening the resultant.',
  },
  {
    id: 'interference-partial',
    name: 'Partial Interference',
    mode: 'interference',
    A: 1,
    f: 1,
    lambda: 4,
    phase2: 90,
    description: 'A quarter-cycle phase offset — neither fully additive nor cancelling.',
  },
  {
    id: 'standing-wave',
    name: 'Standing Wave',
    mode: 'standing',
    A: 1,
    f: 1,
    lambda: 4,
    phase2: 180,
    description: 'Two identical waves traveling in opposite directions create fixed nodes and antinodes.',
  },
]
