// Each level defines the gravity field, launch geometry, and target.
// targetDist is a fraction of canvas width (0–1); targetY is meters above ground.
export const PROJECTILE_LEVELS = [
  {
    id: 'earth',
    name: 'Earth',
    icon: '🌍',
    gravity: 9.8,
    launchHeight: 0,
    targetDist: 0.72,
    targetY: 0,
    radius: 26,
    objective: 'Land the ball inside the marked zone.',
    successFact: 'On Earth, gravity pulls every falling object down at 9.8 m/s² — that constant acceleration is what curves your straight-line velocity into a parabola.',
    failFact: 'Range depends on both speed and angle. Try nudging the angle toward 45° for more distance at the same speed.',
  },
  {
    id: 'moon',
    name: 'Moon',
    icon: '🌕',
    gravity: 1.62,
    launchHeight: 0,
    targetDist: 0.82,
    targetY: 0,
    radius: 26,
    objective: 'Weak gravity means longer flights — reach the far target.',
    successFact: 'The Moon\'s gravity is about 1/6th of Earth\'s, so the same launch speed sends the ball far higher and farther before it falls.',
    failFact: 'With g this low, flight time is much longer. A lower angle can still cover huge distance — try trading some height for range.',
  },
  {
    id: 'mars',
    name: 'Mars',
    icon: '🔴',
    gravity: 3.72,
    launchHeight: 0,
    targetDist: 0.68,
    targetY: 0,
    radius: 24,
    objective: 'Mars gravity sits between Earth and the Moon — recalibrate.',
    successFact: 'Mars gravity (3.72 m/s²) is roughly 38% of Earth\'s, so trajectories arc noticeably higher and longer than on Earth for the same throw.',
    failFact: 'Compare this arc to Earth\'s — same inputs travel farther here because gravity pulls the ball down more slowly.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    icon: '🟠',
    gravity: 24.8,
    launchHeight: 0,
    targetDist: 0.42,
    targetY: 0,
    radius: 22,
    objective: 'Strong gravity crushes your range — throw harder and steeper.',
    successFact: 'Jupiter\'s gravity is over 2.5× Earth\'s, so the ball falls back to the ground much faster, drastically shortening both flight time and range.',
    failFact: 'Under heavy gravity, a higher launch speed matters more than angle. Try increasing velocity before adjusting the angle.',
  },
  {
    id: 'rooftop',
    name: 'Rooftop',
    icon: '🏢',
    gravity: 9.8,
    launchHeight: 100,
    targetDist: 0.78,
    targetY: 0,
    radius: 26,
    objective: 'Launch from a 100 m rooftop and clear the target below.',
    successFact: 'Extra launch height adds free flight time: the ball keeps falling from h₀ = 100 m even after vy would have already brought it to ground level.',
    failFact: 'With launch height in play, range grows even at low angles because there\'s more time for horizontal motion before landing.',
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: '🛠️',
    gravity: 9.8,
    launchHeight: 0,
    targetDist: 0.6,
    targetY: 0,
    radius: 30,
    objective: 'Set your own gravity and hit the target — experiment freely.',
    successFact: 'You control gravity directly here — a great way to test how sensitive range and height are to g.',
    failFact: 'Try adjusting gravity itself, not just velocity and angle, to see its effect on the arc.',
    customGravity: true,
  },
]
