// n = number of rope segments supporting the load (mechanical advantage).
export const PULLEY_LEVELS = [
  {
    id: 'n1',
    name: 'Fixed Pulley',
    n: 1,
    mass: 10,
    g: 9.8,
    objective: 'A single fixed pulley only changes pull direction — no mechanical advantage yet.',
    successFact: 'With n = 1, force in equals force out. A fixed pulley is useful for redirecting effort, but it saves you nothing in force.',
    failFact: 'Remember: F = W / n. With n = 1, the effort force must equal the full weight.',
  },
  {
    id: 'n2',
    name: 'Single Movable',
    n: 2,
    mass: 20,
    g: 9.8,
    objective: 'Adding a movable pulley splits the load across two rope segments.',
    successFact: 'With n = 2, you only need half the weight in effort force — but you pull the rope twice as far.',
    failFact: 'Two rope segments share the load. Divide the weight by 2 to find the required force.',
  },
  {
    id: 'n3',
    name: 'Triple Block',
    n: 3,
    mass: 35,
    g: 9.8,
    objective: 'Three supporting segments — figure out the reduced effort force.',
    successFact: 'Each extra rope segment divides the required force further: F = W/3 here.',
    failFact: 'Count the rope segments actually holding up the load, then divide the weight by that count.',
  },
  {
    id: 'n4',
    name: 'Compound 4x',
    n: 4,
    mass: 48,
    g: 9.8,
    objective: 'A compound block-and-tackle system with four segments.',
    successFact: 'At n = 4, you need only a quarter of the weight in force, at the cost of pulling 4× the rope length.',
    failFact: 'This system quarters the force needed — but check your arithmetic on W = m·g first.',
  },
  {
    id: 'n5',
    name: 'Heavy Lift 5x',
    n: 5,
    mass: 60,
    g: 9.8,
    objective: 'Maximum mechanical advantage in this lab — lift the heaviest load.',
    successFact: 'At n = 5, a 60 kg load that would need 588 N directly only needs about 118 N of effort force.',
    failFact: 'This is the heaviest load in the lab. Work out W = m·g first, then divide by n = 5.',
  },
]
